FROM node:20 As development

WORKDIR /usr/src/scrapping-api

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20 as production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/scrapping-api

COPY package*.json ./


COPY . .

COPY --from=development /usr/src/scrapping-api/dist ./dist

CMD ["node", "dist/main"]